services:
  - type: web
    name: freshflow-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      # Set the following via Render dashboard or CLI
      # - key: MONGO_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      # - key: FRONTEND_URL
      #   sync: false
      # - key: SIMULATE_PROGRESS
      #   value: true
